--https://www.hackerrank.com/challenges/weather-observation-station-5/
SELECT DISTINCT TOP 1 CITY, LEN(CITY)
FROM STATION
ORDER BY LEN(CITY);

SELECT DISTINCT TOP 1 CITY, LEN(CITY)
FROM STATION
ORDER BY LEN(CITY) DESC;
